// <auto-generated />
using System;
using GameServer.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250412113958_ConfigureCascadeDelete")]
    partial class ConfigureCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GameServer.Core.Auth.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GameServer.Core.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PressenceText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoomId");

                    b.ToTable("Entity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GameServer.Core.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("GameServer.Core.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("GameServer.Core.Scripting.ScriptFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("GameServer.Core.Scripting.ScriptInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScriptFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ScriptFileId");

                    b.ToTable("ScriptInstance");
                });

            modelBuilder.Entity("RoomLink", b =>
                {
                    b.Property<int>("ExitsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExitsId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomLink");
                });

            modelBuilder.Entity("GameServer.Core.Player", b =>
                {
                    b.HasBaseType("GameServer.Core.Entity");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoginRoomId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("LoginRoomId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("GameServer.Core.Entity", b =>
                {
                    b.HasOne("GameServer.Core.Room", "CurrentRoom")
                        .WithMany("Entities")
                        .HasForeignKey("CurrentRoomId");

                    b.Navigation("CurrentRoom");
                });

            modelBuilder.Entity("GameServer.Core.Room", b =>
                {
                    b.HasOne("GameServer.Core.Region", null)
                        .WithMany("Rooms")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("GameServer.Core.Scripting.ScriptFile", b =>
                {
                    b.HasOne("GameServer.Core.Auth.Account", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GameServer.Core.Scripting.ScriptInstance", b =>
                {
                    b.HasOne("GameServer.Core.Entity", null)
                        .WithMany("Scripts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameServer.Core.Room", null)
                        .WithMany("Scripts")
                        .HasForeignKey("RoomId");

                    b.HasOne("GameServer.Core.Scripting.ScriptFile", "ScriptFile")
                        .WithMany("Instances")
                        .HasForeignKey("ScriptFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptFile");
                });

            modelBuilder.Entity("RoomLink", b =>
                {
                    b.HasOne("GameServer.Core.Room", null)
                        .WithMany()
                        .HasForeignKey("ExitsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameServer.Core.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Core.Player", b =>
                {
                    b.HasOne("GameServer.Core.Auth.Account", "Account")
                        .WithOne("Player")
                        .HasForeignKey("GameServer.Core.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Core.Entity", null)
                        .WithOne()
                        .HasForeignKey("GameServer.Core.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Core.Room", "LoginRoom")
                        .WithMany()
                        .HasForeignKey("LoginRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("LoginRoom");
                });

            modelBuilder.Entity("GameServer.Core.Auth.Account", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });

            modelBuilder.Entity("GameServer.Core.Entity", b =>
                {
                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("GameServer.Core.Region", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GameServer.Core.Room", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("GameServer.Core.Scripting.ScriptFile", b =>
                {
                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
